exclude: "^docs/|/migrations/|locale/"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--settings-file=pyproject.toml"]

  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        args: ["--config=pyproject.toml"]

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
    -   id: autoflake
        args: ["--config=.flake8"]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ["--config=.flake8"]
        additional_dependencies: [flake8-isort]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: docker compose run --rm -T backend-pokeapi sh -c "pytest ."
        language: system
        pass_filenames: false
        always_run: true

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [feat, fix, test]
