strictness: high
test-warnings: true
doc-warnings: false
member-warnings: false

ignore-paths:
  - __init__.py
  - static/
  - staticfiles/
  - media/
  - migrations/
  - manage.py
  - logs/

uses:
  - django

mccabe:
  disable:
    - MC0001

pylint:
  load-plugins:
    - pylint_django
