# Generated by Django 4.2.8 on 2023-12-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='PokemonAbility',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('ability', models.JSONField(default=list)),
                ('slot', models.PositiveIntegerField(null=True)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Pokemon ability',
                'verbose_name_plural': 'Pokemon abilities',
            },
        ),
        migrations.CreateModel(
            name='PokemonSprite',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('back_default', models.URLField()),
                ('back_female', models.URLField()),
                ('back_shiny', models.URLField()),
                ('back_shiny_female', models.URLField()),
                ('front_default', models.URLField()),
                ('front_female', models.URLField()),
                ('front_shiny', models.URLField()),
                ('front_shiny_female', models.URLField()),
                ('other', models.JSONField(default=dict)),
                ('versions', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Pokemon sprite',
                'verbose_name_plural': 'Pokemon sprites',
            },
        ),
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('slot', models.PositiveIntegerField(null=True)),
                ('type', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Pokemon type',
                'verbose_name_plural': 'Pokemon types',
            },
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'pokeapi_id',
                    models.PositiveIntegerField(
                        db_index=True, verbose_name='Pokedex ID'
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                (
                    'abilities',
                    models.ManyToManyField(to='wrapper.pokemonability'),
                ),
                (
                    'sprites',
                    models.ManyToManyField(to='wrapper.pokemonsprite'),
                ),
                ('types', models.ManyToManyField(to='wrapper.pokemontype')),
            ],
            options={
                'verbose_name': 'Pokemon',
                'verbose_name_plural': 'Pokemons',
            },
        ),
    ]
