# Generated by Django 4.2.8 on 2023-12-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('wrapper', '0001_initial')]

    operations = [
        migrations.AlterField(
            model_name='pokemonsprite',
            name='back_default',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='pokemonsprite',
            name='back_female',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='pokemonsprite',
            name='back_shiny',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='pokemonsprite',
            name='back_shiny_female',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='pokemonsprite',
            name='front_default',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='pokemonsprite',
            name='front_female',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='pokemonsprite',
            name='front_shiny',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='pokemonsprite',
            name='front_shiny_female',
            field=models.URLField(null=True),
        ),
    ]
