# Generated by Django 4.2.8 on 2023-12-12 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('wrapper', '0002_alter_pokemonsprite_back_default_and_more')
    ]

    operations = [
        migrations.RemoveField(model_name='pokemon', name='sprites'),
        migrations.AddField(
            model_name='pokemon',
            name='sprites',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='wrapper.pokemonsprite',
            ),
        ),
    ]
